apiVersion: v1
kind: ConfigMap
metadata:
  name: waf-config
data:
  server {
        listen 80;
        location / {
            proxy_pass http://dvwa-web:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            modsecurity on;
            modsecurity_rules_file /etc/nginx/modsecurity.d/include.conf;
        }
    }
